version: '3.7'

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: secretcookie
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ~/rabbitmq1/data:/var/lib/rabbitmq
      - ~/rabbitmq1/log:/var/log/rabbitmq
    networks:
      - rabbitmq_cluster

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      RABBITMQ_ERLANG_COOKIE: secretcookie
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_CLUSTER_NODE_NAME: rabbit@rabbitmq1
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - ~/rabbitmq2/data:/var/lib/rabbitmq
      - ~/rabbitmq2/log:/var/log/rabbitmq
    networks:
      - rabbitmq_cluster
    depends_on:
      - rabbitmq1

  productdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: whatap
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql/product:/var/lib/mysql
    networks:
      - backend

  orderdb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: whatap
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ~/mysql/order:/var/lib/mysql
    networks:
      - backend

networks:
  rabbitmq_cluster:
    driver: bridge
  backend:
    driver: bridge


