
### 주문 다건 조회
GET http://localhost:8081/api/getOrders/1,2,3,4
Accept: application/json

### 주문 단건 조회
GET http://localhost:8081/api/getOrder/4
Accept: application/json

### 주문 생성
POST http://localhost:8081/api/orderProduct
Content-Type: application/json

{
  "orderItemCreates": [
    {
      "productId": 1,
      "orderQuantity": 1
    },
    {
      "productId": 2,
      "orderQuantity": 1
    }
  ]
}

### 주문 삭제
DELETE http://localhost:8081/api/deleteOrder/7
Accept: application/json


### 주문 변경
PUT http://localhost:8081/api/changeOrder/8
Content-Type: application/json

{
  "orderItemUpdates": [
    {
      "productId": 1,
      "orderQuantity": 1
    },
    {
      "productId": 2,
      "orderQuantity": 1
    }
  ]
}
